name: UI Tests (manual)

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "VAULTWARDEN_URL (e.g., https://<sub>.ngrok-free.app)"
        required: true
      ui_email:
        description: "UI email (optional if secret set)"
        required: false
      ui_password:
        description: "UI password (optional if secret set)"
        required: false
      headless:
        description: "Run headless"
        required: true
        type: choice
        default: "true"
        options: ["true","false"]

permissions:
  contents: write   # needed to push gh-pages
  id-token: write   # harmless default; not strictly required

jobs:
  ui-aws:
    runs-on: ubuntu-latest
    env:
      VAULTWARDEN_URL: ${{ inputs.base_url }}
      VW_EMAIL:        ${{ inputs.ui_email != '' && inputs.ui_email || secrets.VW_EMAIL }}
      VW_PASSWORD:     ${{ inputs.ui_password != '' && inputs.ui_password || secrets.VW_PASSWORD }}
      HEADLESS:        ${{ inputs.headless }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xvfb

      - uses: browser-actions/setup-chrome@v1
        with: { chrome-version: stable }

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-html allure-pytest

      - name: Sanity check env
        run: |
          if [ -z "${VAULTWARDEN_URL}" ]; then
            echo "VAULTWARDEN_URL is empty. Provide base_url input." >&2
            exit 1
          fi
          if [ -z "${VW_EMAIL}" ] || [ -z "${VW_PASSWORD}" ]; then
            echo "VW_EMAIL/VW_PASSWORD missing. Provide inputs or set secrets." >&2
            exit 1
          fi

      - name: Wait for target /alive (ngrok-aware)
        run: |
          set -euo pipefail
          URL="${VAULTWARDEN_URL%/}/alive?ngrok-skip-browser-warning=true"
          echo "Probing: $URL"
          for i in {1..120}; do
            CODE=$(curl -sS -L \
              -H "ngrok-skip-browser-warning: true" \
              -A "vw-ci-bot/1.0" \
              -o resp.html -w "%{http_code}" \
              "$URL" || echo 000)
            if [ "$CODE" = "200" ]; then
              echo "Target is up (200): ${VAULTWARDEN_URL}"
              rm -f resp.html; exit 0
            fi
            if [ "$CODE" = "400" ] && grep -qi "ngrok" resp.html; then
              echo "Ngrok interstitial detected — treating as UP."
              rm -f resp.html; exit 0
            fi
            sleep 2
          done
          echo "Target did not become healthy in time: ${VAULTWARDEN_URL}" >&2
          sed -n '1,120p' resp.html || true
          rm -f resp.html
          exit 1

      - name: Run UI tests (with Allure results)
        run: |
          mkdir -p reports allure-results
          xvfb-run -a python -m pytest -q tests/ui \
            --maxfail=1 \
            --alluredir=allure-results \
            --html=reports/ui.html --self-contained-html \
            --junitxml=reports/ui-junit.xml

      - name: Upload raw reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-reports
          path: |
            reports/*
            allure-results/*

      # Build + publish Allure to gh-pages branch
      - name: Publish Allure report to GitHub Pages
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo Allure URL
        if: always()
        run: |
          REPO="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          echo "Allure report will be available at GitHub Pages (gh-pages branch)."
          echo "Repository: $REPO"
