name: UI Tests (manual)

on:
  workflow_dispatch:
    inputs:
      base_url:
        required: true
      ui_email:
        description: "UI email"
        required: false
      ui_password:
        description: "UI password"
        required: false
      headless:
        description: "Run headless"
        required: true
        type: choice
        default: "true"
        options: ["true","false"]

permissions:
  contents: write

concurrency:
  group: pages-main
  cancel-in-progress: false

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    env:
      VAULTWARDEN_URL: ${{ inputs.base_url }}
      VW_EMAIL:        ${{ inputs.ui_email != '' && inputs.ui_email || secrets.VW_EMAIL }}
      VW_PASSWORD:     ${{ inputs.ui_password != '' && inputs.ui_password || secrets.VW_PASSWORD }}
      HEADLESS:        ${{ inputs.headless }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xvfb

      - uses: browser-actions/setup-chrome@v1
        with: { chrome-version: stable }

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest-html allure-pytest

      - name: Sanity check env
        run: |
          if [ -z "${VAULTWARDEN_URL}" ]; then
            echo "VAULTWARDEN_URL is empty. Provide base_url input." >&2
            exit 1
          fi
          if [ -z "${VW_EMAIL}" ] || [ -z "${VW_PASSWORD}" ]; then
            echo "VW_EMAIL/VW_PASSWORD missing. Provide inputs or set secrets." >&2
            exit 1
          fi

      - name: Wait for target /alive (ngrok-aware)
        run: |
          set -euo pipefail
          URL="${VAULTWARDEN_URL%/}/alive?ngrok-skip-browser-warning=true"
          echo "Probing: $URL"
          for i in {1..120}; do
            CODE=$(curl -sS -L \
              -H "ngrok-skip-browser-warning: true" \
              -A "vw-ci-bot/1.0" \
              -o resp.html -w "%{http_code}" \
              "$URL" || echo 000)
            if [ "$CODE" = "200" ]; then
              echo "Target is up (200): ${VAULTWARDEN_URL}"
              rm -f resp.html; exit 0
            fi
            if [ "$CODE" = "400" ] && grep -qi "ngrok" resp.html; then
              echo "Ngrok interstitial detected — treating as UP."
              rm -f resp.html; exit 0
            fi
            sleep 2
          done
          echo "Target did not become healthy in time: ${VAULTWARDEN_URL}" >&2
          sed -n '1,120p' resp.html || true
          rm -f resp.html
          exit 1

      - name: Run UI tests (with Allure results)
        run: |
          mkdir -p reports allure-results
          xvfb-run -a python -m pytest -q tests/ui \
            --maxfail=1 \
            --alluredir=allure-results \
            --html=reports/ui.html --self-contained-html \
            --junitxml=reports/ui-junit.xml

      - name: Upload raw reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-reports
          path: |
            reports/*
            allure-results/*

      - name: Set up Java (for Allure CLI)
        if: always()
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Allure CLI
        if: always()
        run: npm i -g allure-commandline --no-audit --no-fund

      - name: Generate Allure HTML
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report
          test -f allure-report/index.html
          touch allure-report/.nojekyll

      # Publish into /docs/ui without touching /docs/ci
      - name: Commit Allure report to /docs/ui (main)
        if: always()
        run: |
          set -euo pipefail
          mkdir -p docs/ui
          rsync -a --delete allure-report/ docs/ui/
          if [ ! -f docs/index.html ]; then
            printf '%s\n' \
              '<!doctype html><meta charset="utf-8">' \
              '<title>Allure Reports</title>' \
              '<h1>Allure Reports</h1>' \
              '<ul>' \
              '  <li><a href="./ci/">API CI Report</a></li>' \
              '  <li><a href="./ui/">UI Manual Report</a></li>' \
              '</ul>' > docs/index.html
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/ui docs/index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs(ui): publish Allure report to /docs/ui [skip ci]"
            git pull --rebase
            git push
          fi
